name: CI-CD AgroVerde

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Verificar Docker
        run: docker --version

      - name: Construir imagem Docker
        run: docker build -t agroverde .

      - name: Copiar index.html para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "index.html"
          target: "/tmp"

      - name: Atualizar site na EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp /tmp/index.html /var/www/html/index.html
            sudo systemctl restart nginx

      - name: Finalizado
        run: echo "Deploy realizado com sucesso!"
